{application,foobar,
             [{description,[]},
              {vsn,"c6ecfd3"},
              {registered,[]},
              {applications,[kernel,stdlib,cowboy]},
              {mod,{foobar_app,[]}},
              {env,[]},
              {modules,[foobar_app,foobar_index,foobar_index_dtl,
                        foobar_sup]}]}.
